### PR TITLE
added Imin and Imax to the pin entries

### PR DESCRIPTION
**Pull request by areda0**

### CODE REVIEW

**Review by RTimothyEdwards — COMMENTED** [review]
I'm okay with this change, although on general principles:
(1) The key should be 'Imax' (capital "I") to be consistend with 'Vmax'
(2) There really isn't a concept of "minimum current".  Normally it would depend on the current direction and be one or both of "Isource(max)" and "Isink(max)" (or something like that).

@mole99 :  The real error here is that pin entries are rather free-form and should have whatever key:value pairs seem appropriate.  I wanted it that way precisely because in some cases, Vmin/Vmax is important, and in some cases Isource/Isink is important.  The "pins" section really has only two purposes:  (1) Cross-check against the schematic symbol and report on pin inconsistencies, and (2) Print the information into the markdown summary.  For the latter, CACE should not care about the keys;  it should just tabulate the keys and values.  (Note that ideally, creating a simple skeleton of the pin section from content in either the schematic symbol or a layout LEF file should be possible, is easy to do, and then only leaves filling out the description for the designer.  I would really like such a feature for cheetah_v3_analog, which has hundreds of pins that I don't want to have to enter all the information for by hand.)

So, in short, I think the real correction here should be that cace_write.py lines 96 and following should be:

```
                known_fields = [
                    'display', 'description', 'type', 'direction', 'Vmin', 'Vmax', note
                ]

                for entry in datasheet['pins'][pin]:
                    ofile.write(
                        f' + {entry}: {datasheet["pins"][pin][entry]}\n'
                    )
                    if entry not in known_fields:
                        warn(f'Unknown entry in pins: {entry}')
```
although I would also point out that you have deleted my original code behavior, which was to write out all known fields first, followed by any unknown fields, which I did on purpose.

The same method should be applied to the "authorship" block, which also should be free-form and gets output to the markdown summary as-is, with any fields that the designer wishes to put there.  Unknown fields should flag that they are not recognized, but should be output to the file anyway, preferably after the known fields.  This would allow, for example, "organization" in addition to "company" and "institution" (although that should probably just be added to the list of known fields).

"pins" and "authorship" are probably the only two sections that I would consider to be "free-form".

**Comment by areda0** [comment]
I agree with Leo that "pins" and "authorship" should be free-form but then wouldn't it be better not to signal unknown-fields in a warning?

**Comment by RTimothyEdwards** [comment]
@areda0 :  That was my comment about free-form fields.  I could go either way, with or without a warning message.  I think you're probably right, and I'd add that the more important thing is to check that certain entries are present---because an IP block should not be considered verifiable or reusable unless it has a designer name and a license, for example.  Those things should probably not be checked as part of writing the markdown output, but rather checked as part of a "precheck" step like we do for Efabless chipIgnite submissions, which would just be another "parameter" like DRC and LVS checks.

Obviously there are many ways to slice this cake.

**Comment by mole99** [comment]
Hi @areda0, the documentation changes for `Imin`/`Imax` are missing in this PR.

Hi @tim, I still think it has a benefit to check against known keys so that the entries are more consistent from IP to IP and to prevent people from inventing different ways to spell the same key (e.g. `imax` vs `Imax`). If any important keys are missing we can easily add them. For anything more free-form, there's always the `note` entry. But I agree that all entries should be written out to the Markdown summary.

I also agree that the function for the Markdown summary is not the right place to check these entries, but neither is a parameter.

This should really be done after the datasheet has been parsed. There is already the right function where this can be added: `validate_datasheet` in `cace_read`. If this is alright for you, I can add this to my to-do list, but I would suggest that Ahmed still finishes this PR the way it is currently implemented.

**Comment by mole99** [comment]
Hi @areda0, is this PR still valid? It's missing documentation changes.

**Comment by areda0** [comment]
@mole99  please check the latest commit. 
I think we need to consider Tim's suggestion from the 1st comment that the pins should be automatically added from the symbol or the Layout. Is that something easily doable?

**Comment by mole99** [comment]
@areda0 It is not trivial. How would we edit the datasheet, since if we dump the yaml, all structure and comments would be lost? For starter, you could create a separate issue and we can discuss it on thursday.

**Comment by areda0** [comment]
@mole99 let's wait till we discuss it in more details and then decide whether we wish to create an issue for this one.

**Comment by mole99** [comment]
Merging after discussion.

**Pull request merged**
